# Generated by Django 5.0.4 on 2024-04-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.JSONField(default=list, verbose_name=models.IntegerField()),
                ),
                ("color", models.JSONField(default=list)),
                (
                    "url",
                    models.CharField(
                        help_text="Product Detail Page URL", max_length=255
                    ),
                ),
                ("image_urls", models.JSONField(default=list)),
                (
                    "activity",
                    models.JSONField(
                        default=list,
                        help_text="Intended use the product is designed for",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category_hierarchy", models.JSONField(default=list)),
                (
                    "default_sku",
                    models.CharField(
                        help_text="Unique identifier, Stock Keeping Unit",
                        max_length=100,
                    ),
                ),
                ("availability", models.JSONField(default=list)),
                ("currency_code", models.CharField(max_length=100)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
